channels:
- conda-forge
dependencies:
- python=3.8.13
- pip
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - lz4==3.1.10
  - mypy-extensions==0.4.3
  - pathlib==1.0.1
  - psutil==5.9.1
  - scikit-learn==1.0.1
  - xgboost==1.5.0
name: mlflow-env
