services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    depends_on:
      - api

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data:
